services:
  - type: web
    name: codex-cloud-chat
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: CODEX_ENV_OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
